<?php
    $statements = $this->getSqlStatements();
?>

<?php if (!empty($statements)) { ?>
    <?php foreach ($statements as $statement) { ?>
        <span class="fs-label">
            <?php echo $this->renderTrace($statement->getTrace()); ?>
        </span>
        <span class="fs-label">
            <span class="fs-pre-wrap">wrap</span>
            <pre class="fs-dark"><?php echo $statement->getStatement(); ?></pre>
        </span>
        <span class="fs-label">
            <?php echo $statement->getTime(); ?> milliseconds
        </span>
        <hr class="fs-hr">
    <?php } ?>
<?php } else { ?>
    <p>No SQL Statements Executed...</p>
<?php } ?>
