<?php
    $statements = $this->getSqlStatements();
?>

<?php if (!empty($statements)) { ?>
    <?php foreach ($statements as $statement) { ?>
        <span class="fs-label">
            <?php
                $traces = $statement->getTrace();
                foreach ($traces as $index => $trace) {
                    $traceLine = '#' . $index . ' ';

                    if (!empty($trace['file'])) {
                        $traceLine .= $trace['file'];
                    }

                    if (!empty($trace['line'])) {
                        $traceLine .= '(' . $trace['line'] . ') ';
                    }

                    if (!empty($trace['class'])) {
                        $traceLine .= $trace['class'] . '::';
                    }

                    $traceLine .= $trace['function'] . '()'
                        . '<br>';
                    echo $traceLine;
                }
            ?>
        </span>
        <span class="fs-label">
            <span class="fs-pre-wrap">wrap</span>
            <pre class="fs-dark"><?php echo $statement->getStatement(); ?></pre>
        </span>
        <span class="fs-label">
            <?php echo $statement->getTime(); ?> milliseconds
        </span>
        <hr class="fs-hr" style="margin: 25px 0; color: #464646; border-top: 2px dashed; background-color: #f0f0f0;">
    <?php } ?>
<?php } else { ?>
    <p>No SQL Statements Executed...</p>
<?php } ?>
